# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI and Publishing

on:
  push:
    branches: [master]
    tags:
      - v*.*.*
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - env:
          ST_TEST_ACCESS_TOKEN: ${{ secrets.ST_TEST_ACCESS_TOKEN }}
        run: printf "$ST_TEST_ACCESS_TOKEN" > accessToken
      - run: npm run build --if-present
      - run: npm test

  rollback-release-tag:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'refs/tags/v') && failure()
    steps:
      - run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Remove tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "stgen@users.noreply.github.com"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git fetch --tags
          git revert $SOURCE_TAG
          git push
          git push github :$GITHUB_REF

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.SOURCE_TAG }}
          draft: false
          prerelease: ${{ contains(env.SOURCE_TAG, '-') }}

  publish-npm:
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
